# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: keyval.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'keyval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckeyval.proto\x12\x05proto\"\"\n\x04Pack\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t2T\n\x06KeyVal\x12!\n\x03Set\x12\x0b.proto.Pack\x1a\x0b.proto.Pack\"\x00\x12\'\n\x03Get\x12\x11.proto.GetRequest\x1a\x0b.proto.Pack\"\x00\x42!Z\x1fgithub.com/tashima42/raft/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037github.com/tashima42/raft/proto'
  _globals['_PACK']._serialized_start=23
  _globals['_PACK']._serialized_end=57
  _globals['_GETREQUEST']._serialized_start=59
  _globals['_GETREQUEST']._serialized_end=84
  _globals['_KEYVAL']._serialized_start=86
  _globals['_KEYVAL']._serialized_end=170
# @@protoc_insertion_point(module_scope)
