// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: keyval.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyVal_Set_FullMethodName = "/proto.KeyVal/Set"
	KeyVal_Get_FullMethodName = "/proto.KeyVal/Get"
)

// KeyValClient is the client API for KeyVal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyValClient interface {
	Set(ctx context.Context, in *Pack, opts ...grpc.CallOption) (*Pack, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Pack, error)
}

type keyValClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyValClient(cc grpc.ClientConnInterface) KeyValClient {
	return &keyValClient{cc}
}

func (c *keyValClient) Set(ctx context.Context, in *Pack, opts ...grpc.CallOption) (*Pack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pack)
	err := c.cc.Invoke(ctx, KeyVal_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Pack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pack)
	err := c.cc.Invoke(ctx, KeyVal_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyValServer is the server API for KeyVal service.
// All implementations must embed UnimplementedKeyValServer
// for forward compatibility.
type KeyValServer interface {
	Set(context.Context, *Pack) (*Pack, error)
	Get(context.Context, *GetRequest) (*Pack, error)
	mustEmbedUnimplementedKeyValServer()
}

// UnimplementedKeyValServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyValServer struct{}

func (UnimplementedKeyValServer) Set(context.Context, *Pack) (*Pack, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedKeyValServer) Get(context.Context, *GetRequest) (*Pack, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKeyValServer) mustEmbedUnimplementedKeyValServer() {}
func (UnimplementedKeyValServer) testEmbeddedByValue()                {}

// UnsafeKeyValServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyValServer will
// result in compilation errors.
type UnsafeKeyValServer interface {
	mustEmbedUnimplementedKeyValServer()
}

func RegisterKeyValServer(s grpc.ServiceRegistrar, srv KeyValServer) {
	// If the following call panics, it indicates UnimplementedKeyValServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyVal_ServiceDesc, srv)
}

func _KeyVal_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pack)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyVal_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValServer).Set(ctx, req.(*Pack))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyVal_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyVal_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyVal_ServiceDesc is the grpc.ServiceDesc for KeyVal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyVal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.KeyVal",
	HandlerType: (*KeyValServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _KeyVal_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _KeyVal_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keyval.proto",
}
